simpleblog/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'posts#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'

  resources :posts do
    resources :comments
  end


end

simpleblog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

simpleblog/app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
    validates :title, presence: true, 
                        length: {minimum: 5}
end

simpleblog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

simpleblog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(comment_params)
        redirect_to post_path(@post)        
    end

    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)
    end


    private

    def comment_params
        params.require(:comment).permit(:username, :body)
    end



end

simpleblog/app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
        @title = 'About Us';
        @content = 'This is the about page'
    end
end

simpleblog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index 
        @posts = Post.all
    end

    def show
        @post = Post.find(params[:id])
    end

    def new
        @post = Post.new
    end

    def edit    
        @post = Post.find(params[:id])
    end

    def update    
        @post = Post.find(params[:id])
        
        if (@post.update(post_params))
            redirect_to @post
        else
            render 'edit'
        end
    end


    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end

    def create
        # render plain: params[:post].inspect
        @post = Post.new(post_params)
        
        if (@post.save)
            redirect_to @post
        else
            render 'new'
        end
    end

    private 
    
    def post_params
        params.require(:post).permit(:title, :body)
    end

end

simpleblog/app/helpers/application_helper.rb
module ApplicationHelper
end

simpleblog/app/helpers/comments_helper.rb
module CommentsHelper
end

simpleblog/app/helpers/pages_helper.rb
module PagesHelper
end

simpleblog/app/helpers/posts_helper.rb
module PostsHelper
end

simpleblog/app/views/comments/_comments.html.erb
<h3>Comments</h3>
<% @post.comments.each do |comment| %>
    <div class="card">
        <p><strong><%= comment.username %></strong>: <%=comment.body%></p>
        <%= link_to "[X]", [comment.post, comment], 
                                   method: :delete, 
                                    data: {confirm: 'Are you sure?'} %>
    </div>
<% end %>

simpleblog/app/views/comments/_form.html.erb
<h3>Add Comment</h3>
<%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
        <%= f.label :username %><br />
        <%= f.text_field(:username, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.label :body %><br />
        <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>
    <p>
        <%= f.submit({:class => 'btn btn-info'}) %>
    </p>
<% end %>

simpleblog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simpleblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>


    <nav class="navbar navbar-expand navbar-light bg-light">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Simple Blog</a>
      </div>

      <div class="container collapse navbar-collapse" id="navbarsExample02">

        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Home", home_path %>
          </li>
        </ul>

        <ul class="navbar-nav mr-auto navbar-right">
          <li class="nav-item">
            <%= link_to "Create Post", new_post_path %>
          </li>
        </ul>
      </div>
    </nav>
    <br />

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

simpleblog/app/views/pages/about.html.erb
<h1><%= @title %></h1>

<p><%= @content %></p>

simpleblog/app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for :post, url: post_path, method: :patch do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg%></div>
        <% end %>
    <% end %>

    <p>
        <%= f.label :title %><br />
        <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>

    <p>
        <%= f.label :body %><br />
        <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>

    <p>
        <%= f.submit({:class => 'btn btn-primary'}) %>
    </p>

<% end %>

simpleblog/app/views/posts/index.html.erb
<h1>Blog posts</h1>
<% @posts.each do |post| %>
    <div class="card-body">
        <h3><%= post.title %></h3>
        <p><%= post.body %></p>
        <%= link_to "Read More", post_path(post), :class => 'btn btn-info' %>
    </div>
<% end %>

simpleblog/app/views/posts/new.html.erb
<h1>Add Post</h1>
<%= form_for :post, url: posts_path do |f| %>
    <% if @post.errors.any? %>
        <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg%></div>
        <% end %>
    <% end %>

    <p>
        <%= f.label :title %><br />
        <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>

    <p>
        <%= f.label :body %><br />
        <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>

    <p>
        <%= f.submit({:class => 'btn btn-primary'}) %>
    </p>

<% end %>

simpleblog/app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>
<hr />
<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-info' %>
<%= link_to "Delete", post_path(@post), 
                            method: :delete,
                            data: {confirm: 'Are you sure?'}, 
                            :class => 'btn btn-danger' %>
<hr />

<%= render 'comments/comments' %>
<br />
<%= render 'comments/form' %>